# Site settings
title: snugg.ie
description: "Beep-boop. Beep-boop. Here is Evie Snuggle's site! üçµüå∏"


# Social settings
500px:
  url: https://github.com/Snuggle
facebook:
  url: https://github.com/Snuggle
github:
  url: https://github.com/Snuggle
gitlab:
  url: https://github.com/Snuggle
instagram:
  url: https://github.com/Snuggle
linkedin:
  url: https://github.com/Snuggle
medium:
  url: https://github.com/Snuggle
pinterest:
  url: https://github.com/Snuggle
slack:
  url: https://github.com/Snuggle
snapchat:
  url: https://github.com/Snuggle
twitter:
  url: https://github.com/Snuggle

# Optional elements
logo: /assets/images/sprinkles/large/logo.png
favicon: /assets/images/sprinkles/favicons/normalfavicon-polyres.ico

permalink: /posts/:title

# Collections
collections:
  home_sections:
    output: false
  pages:
    output: true
    permalink: /:title

# Build settings
markdown: kramdown
sass:
  style: compressed

plugins:
  - jekyll-redirect-from

# Publication settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
author: Evie Snuggle
copyright:
  holder: Evie Snuggle
  license: CC0

# Exclude from processing
